apiVersion: v1

name: cert-manager-csi-driver
type: application
description: A Helm chart for cert-manager-csi-driver

home: https://github.com/cert-manager/csi-driver
maintainers:
- name: joshvanl
  email: joshua.vanleeuwen@jetstack.io
  url: https://cert-manager.io
sources:
- https://github.com/cert-manager/csi-driver

appVersion: v0.1.1
version: v0.1.1
