image:
  # -- Target image repository.
  repository: quay.io/jetstack/cert-manager-csi-driver
  # -- Target image version tag.
  tag: v0.1.1
  # -- Kubernetes imagePullPolicy on DaemonSet.
  pullPolicy: IfNotPresent

app:
  # -- Verbosity of cert-manager-csi-driver logging.
  logLevel: 1 # 1-5
  # -- Options for CSI driver
  driver:
    # -- Name of the driver which will be registered with Kubernetes.
    name: csi.cert-manager.io
    # -- If enabled, will use CSI token request for creating
    # CertificateRequests. CertificateRequests will be created via mounting
    # pod's service accounts.
    useTokenRequest: false

resources: {}
  # -- Kubernetes pod resource limits for cert-manager-csi-driver
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # -- Kubernetes pod memory resource requests for cert-manager-csi-driver
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
