apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: selfsigning-issuer
  namespace: sandbox
spec:
  selfSigned: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: sandbox
---
apiVersion: v1
kind: Pod
metadata:
  name: my-csi-app
  namespace: sandbox
spec:
  serviceName: my-service
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/tls"
        name: tls
      command: [ "sleep", "1000000" ]
  volumes:
    - name: tls
      csi:
        driver: csi.certmanager.k8s.io
        volumeAttributes:
              csi.certmanager.k8s.io/issuer-name: selfsigning-issuer
              csi.certmanager.k8s.io/dns-names: my-service.sandbox.svc.cluster.local
